language: generic
os:
  - linux
  - osx
sudo: false
before_install:
  - git submodule update --init --recursive
install:
  # source because it sets up env vars on some platforms
  - source ci/travis/travis_install.sh
script:
  - ci/travis/travis_script.sh
env:
  matrix:
    - YCM_PYTHON_VERSION=2.7 YCM_FLAKE8=true
    # Since 3.0.4, Flake8 is not working anymore on Python 2.6.
    - YCM_PYTHON_VERSION=2.6 YCM_FLAKE8=false
    - YCM_PYTHON_VERSION=3.3 YCM_FLAKE8=true
matrix:
  exclude:
    - os: osx
      env: YCM_PYTHON_VERSION=2.6 YCM_FLAKE8=false
addons:
  apt:
    sources:
     # The Travis apt source whitelist can be found here:
     #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
     - ubuntu-toolchain-r-test  # for new libstdc++
     - george-edison55-precise-backports # for a more recent version of cmake (3.2.3)
    packages:
     - cmake-data
     - cmake
     - ninja-build
     # Everything below is a Python build dep (though it depends on Python
     # version). We need them because pyenv builds Python.
     - libssl-dev
     - zlib1g-dev
     - libbz2-dev
     - libreadline-dev
     - libsqlite3-dev
     - wget
     - curl
     - llvm
     - libncurses5-dev
     - libncursesw5-dev
cache:
  directories:
    - $HOME/.cache/pip  # Python packages from pip
    - $HOME/.pyenv  # pyenv
