.TH "breakpoint" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breakpoint \- breakpoint - Launch debug mode 
.SH "breakpoint - Launch debug mode"
.PP
.SS "Synopsis"
\fCbreakpoint\fP
.SS "Description"
\fCbreakpoint\fP is used to halt a running script and launch an interactive debugging prompt\&.
.PP
For more details, see \fCDebugging fish scripts\fP in the \fCfish\fP manual\&.
.PP
There are no parameters for \fCbreakpoint\fP\&. 
