.TH "break" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
break \- break - stop the current inner loop 
.SH "break - stop the current inner loop"
.PP
.SS "Synopsis"
\fCLOOP_CONSTRUCT; [COMMANDS\&.\&.\&.] break; [COMMANDS\&.\&.\&.] end\fP
.SS "Description"
\fCbreak\fP halts a currently running loop, such as a \fCfor\fP loop or a \fCwhile\fP loop\&. It is usually added inside of a conditional block such as an \fCif\fP statement or a \fCswitch\fP statement\&.
.PP
There are no parameters for \fCbreak\fP\&.
.SS "Example"
The following code searches all \&.c files for 'smurf', and halts at the first occurrence\&.
.PP
.PP
.nf

for i in *\&.c
    if grep smurf $i
        echo Smurfs are present in $i
        break
    end
end
.fi
.PP
 
