.TH "contains" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contains \- contains - test if a word is present in a list 
.SH "contains - test if a word is present in a list"
.PP
.SS "Synopsis"
\fCcontains [OPTIONS] KEY [VALUES\&.\&.\&.]\fP
.SS "Description"
\fCcontains\fP tests whether the set \fCVALUES\fP contains the string \fCKEY\fP\&. If so, \fCcontains\fP exits with status 0; if not, it exits with status 1\&.
.PP
The following options are available:
.PP
.IP "\(bu" 2
\fC-i\fP or \fC--index\fP print the word index
.IP "\(bu" 2
\fC-h\fP or \fC--help\fP display this message
.PP
.SS "Example"
.PP
.nf

for i in ~/bin /usr/local/bin
        if not contains $i $PATH
                set PATH $PATH $i
        end
end
.fi
.PP
.PP
The above code tests if \fC~/bin\fP and \fC/usr/local/bin\fP are in the path and adds them if not\&. 
