.TH "continue" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
continue \- continue - skip the remainder of the current iteration of the current inner loop 
.SH "continue - skip the remainder of the current iteration of the current inner loop"
.PP
.SS "Synopsis"
\fCLOOP_CONSTRUCT; [COMMANDS\&.\&.\&.;] continue; [COMMANDS\&.\&.\&.;] end\fP
.SS "Description"
\fCcontinue\fP skips the remainder of the current iteration of the current inner loop, such as a \fCfor\fP loop or a \fCwhile\fP loop\&. It is usually added inside of a conditional block such as an \fCif\fP statement or a \fCswitch\fP statement\&.
.SS "Example"
The following code removes all tmp files that do not contain the word smurf\&.
.PP
.PP
.nf

for i in *\&.tmp
    if grep smurf $i
        continue
    end
    rm $i
end
.fi
.PP
 
