.TH "dirh" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dirh \- dirh - print directory history 
.SH "dirh - print directory history"
.PP
.SS "Synopsis"
\fCdirh\fP
.SS "Description"
\fCdirh\fP prints the current directory history\&. The current position in the history is highlighted using the color defined in the \fCfish_color_history_current\fP environment variable\&.
.PP
\fCdirh\fP does not accept any parameters\&. 
