.TH "dirs" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dirs \- dirs - print directory stack 
.SH "dirs - print directory stack"
.PP
.SS "Synopsis"
\fCdirs\fP
.SS "Description"
\fCdirs\fP prints the current directory stack, as created by the \fC\fCpushd\fP\fP command\&.
.PP
\fCdirs\fP does not accept any parameters\&. 
