.TH "else" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
else \- else - execute command if a condition is not met 
.SH "else - execute command if a condition is not met"
.PP
.SS "Synopsis"
\fCif CONDITION; COMMANDS_TRUE\&.\&.\&.; [else; COMMANDS_FALSE\&.\&.\&.;] end\fP
.SS "Description"
\fCif\fP will execute the command \fCCONDITION\fP\&. If the condition's exit status is 0, the commands \fCCOMMANDS_TRUE\fP will execute\&. If it is not 0 and \fCelse\fP is given, \fCCOMMANDS_FALSE\fP will be executed\&.
.SS "Example"
The following code tests whether a file \fCfoo\&.txt\fP exists as a regular file\&.
.PP
.PP
.nf

if test -f foo\&.txt
    echo foo\&.txt exists
else
    echo foo\&.txt does not exist
end
.fi
.PP
 
