.TH "emit" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emit \- emit - Emit a generic event 
.SH "emit - Emit a generic event"
.PP
.SS "Synopsis"
\fCemit EVENT_NAME [ARGUMENTS\&.\&.\&.]\fP
.SS "Description"
\fCemit\fP emits, or fires, an event\&. Events are delivered to, or caught by, special functions called event handlers\&. The arguments are passed to the event handlers as function arguments\&.
.SS "Example"
The following code first defines an event handler for the generic event named 'test_event', and then emits an event of that type\&.
.PP
.PP
.nf
function event_test --on-event test_event
    echo event test: $argv
end
.fi
.PP
.PP
.PP
.nf
emit test_event something
.fi
.PP
 
