.TH "exit" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exit \- exit - exit the shell 
.SH "exit - exit the shell"
.PP
.SS "Synopsis"
\fCexit [STATUS]\fP
.SS "Description"
\fCexit\fP causes fish to exit\&. If \fCSTATUS\fP is supplied, it will be converted to an integer and used as the exit code\&. Otherwise, the exit code will be that of the last command executed\&.
.PP
If exit is called while sourcing a file (using the \fC\&.\fP builtin) the rest of the file will be skipped, but the shell itself will not exit\&. 
