.TH "fish_pager" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fish_pager \- fish_pager - internal command used by fish 
.SH "fish_pager - internal command used by fish"
.PP
.SS "Description"
\fCfish_pager\fP is used internally by fish\&. It should not be used by other commands, as its interface is liable to change in the future\&. 
