.TH "funced" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
funced \- funced - edit a function interactively 
.SH "funced - edit a function interactively"
.PP
.SS "Synopsis"
\fCfunced [OPTIONS] NAME\fP
.SS "Description"
\fCfunced\fP provides an interface to edit the definition of the function \fCNAME\fP\&.
.PP
If the \fC$EDITOR\fP environment variable is set, it will be used as the program to edit the function\&. Otherwise, a built-in editor will be used\&.
.PP
If there is no function called \fCNAME\fP a new function will be created with the specified name
.PP
.IP "\(bu" 2
\fC-e command\fP or \fC--editor command\fP Open the function body inside the text editor given by the command (for example, 'vi')\&. The command 'fish' will use the built-in editor\&.
.IP "\(bu" 2
\fC-i\fP or \fC--interactive\fP Open function body in the built-in editor\&. 
.PP

