.TH "funcsave" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
funcsave \- funcsave - save the definition of a function to the user's autoload directory 
.SH "funcsave - save the definition of a function to the user's autoload directory"
.PP
.SS "Synopsis"
\fCfuncsave FUNCTION_NAME\fP
.SS "Description"
\fCfuncsave\fP saves the current definition of a function to a file in the fish configuration directory\&. This function will be automatically loaded by current and future fish sessions\&. This can be useful if you have interactively created a new function and wish to save it for later use\&. 
