.TH "isatty" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isatty \- isatty - test if the specified file descriptor is a tty 
.SH "isatty - test if the specified file descriptor is a tty"
.PP
.SS "Synopsis"
\fCisatty [FILE DESCRIPTOR]\fP
.SS "Description"
\fCisatty\fP tests if a file descriptor is a tty\&.
.PP
\fCFILE DESCRIPTOR\fP may be either the number of a file descriptor, or one of the strings \fCstdin\fP, \fCstdout\fP and \fCstderr\fP\&.
.PP
If the specified file descriptor is a tty, the exit status of the command is zero\&. Otherwise, it is non-zero\&. 
