.TH "mimedb" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mimedb \- mimedb - lookup file information via the mime database 
.SH "mimedb - lookup file information via the mime database"
.PP
.SS "Synopsis"
\fCmimedb [OPTIONS] FILES\&.\&.\&.\fP
.SS "Description"
\fCmimedb\fP queries the MIME type database and the \fC\fP\&.desktop files installed on the system in order to find information on the files listed in \fCFILES\fP\&. The information that \fCmimedb\fP can retrieve includes the MIME type for a file, a description of the type, and the default action that can be performed on the file\&. \fCmimedb\fP can also be used to launch the default action for this file\&.
.PP
The following options are available:
.PP
.IP "\(bu" 2
\fC-t\fP, \fC--input-file-data\fP determines the files' type both by their filename and by their contents (default behaviour)\&.
.IP "\(bu" 2
\fC-f\fP, \fC--input-filename\fP determines the files' type by their filename\&.
.IP "\(bu" 2
\fC-i\fP, \fC--input-mime\fP specifies that the arguments are not files, but MIME types\&.
.IP "\(bu" 2
\fC-m\fP, \fC--output-mime\fP outputs the MIME type of each file (default behaviour)\&.
.IP "\(bu" 2
\fC-f\fP, \fC--output-description\fP outputs the description of each MIME type\&.
.IP "\(bu" 2
\fC-a\fP, \fC--output-action\fP outputs the default action of each MIME type\&.
.IP "\(bu" 2
\fC-l\fP, \fC--launch\fP launches the default action for the specified files\&.
.IP "\(bu" 2
\fC-h\fP, \fC--help\fP displays a help message and exit\&.
.IP "\(bu" 2
\fC-v\fP, \fC--version\fP displays the version number and exits\&. 
.PP

