.TH "open" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
open \- open - open file in its default application 
.SH "open - open file in its default application"
.PP
.SS "Synopsis"
\fCopen FILES\&.\&.\&.\fP
.SS "Description"
\fCopen\fP opens a file in its default application, using the \fCxdg-open\fP command if it exists, or else the \fCmimedb\fP command\&.
.SS "Example"
\fCopen *\&.txt\fP opens all the text files in the current directory using your system's default text editor\&. 
