.TH "popd" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
popd \- popd - move through directory stack 
.SH "popd - move through directory stack"
.PP
.SS "Synopsis"
\fCpopd\fP
.SS "Description"
\fCpopd\fP removes the top directory from the directory stack and changes the working directory to the new top directory\&. Use \fC\fCpushd\fP\fP to add directories to the stack\&.
.SS "Example"
.PP
.nf

pushd /usr/src
.SH "Working directory is now /usr/src"
.PP
.fi
.PP
.PP
.PP
.nf

.SH "Directory stack contains /usr/src"
.PP
.fi
.PP
.PP
.PP
.nf

pushd /usr/src/fish-shell
.SH "Working directory is now /usr/src/fish-shell"
.PP
.fi
.PP
.PP
.PP
.nf

.SH "Directory stack contains /usr/src /usr/src/fish-shell"
.PP
.fi
.PP
.PP
.PP
.nf

popd
.SH "Working directory is now /usr/src"
.PP
.fi
.PP
.PP
.PP
.nf

.SH "Directory stack contains /usr/src"
.PP
.fi
.PP
.PP
.PP
.nf

.fi
.PP
 
