.TH "pushd" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pushd \- pushd - push directory to directory stack 
.SH "pushd - push directory to directory stack"
.PP
.SS "Synopsis"
\fCpushd [DIRECTORY]\fP
.SS "Description"
The \fCpushd\fP function adds \fCDIRECTORY\fP to the top of the directory stack and makes it the current working directory\&. \fC\fCpopd\fP\fP will pop it off and return to the original directory\&.
.SS "Example"
.PP
.nf

pushd /usr/src
.SH "Working directory is now /usr/src"
.PP
.fi
.PP
.PP
.PP
.nf

.SH "Directory stack contains /usr/src"
.PP
.fi
.PP
.PP
.PP
.nf

pushd /usr/src/fish-shell
.SH "Working directory is now /usr/src/fish-shell"
.PP
.fi
.PP
.PP
.PP
.nf

.SH "Directory stack contains /usr/src /usr/src/fish-shell"
.PP
.fi
.PP
.PP
.PP
.nf

popd
.SH "Working directory is now /usr/src"
.PP
.fi
.PP
.PP
.PP
.nf

.SH "Directory stack contains /usr/src"
.PP
.fi
.PP
.PP
.PP
.nf

.fi
.PP
 
