.TH "pwd" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pwd \- pwd - output the current working directory 
.SH "pwd - output the current working directory"
.PP
.SS "Synopsis"
\fCpwd\fP
.SS "Description"
\fCpwd\fP outputs (prints) the current working directory\&.
.PP
Note that \fCfish\fP always resolves symbolic links in the current directory path\&. 
