.TH "random" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
random \- random - generate random number 
.SH "random - generate random number"
.PP
.SS "Synopsis"
\fCrandom [SEED]\fP
.SS "Description"
\fCrandom\fP outputs a random number from 0 to 32766, inclusive\&.
.PP
If a \fCSEED\fP value is provided, it is used to seed the random number generator, and no output will be produced\&. This can be useful for debugging purposes, where it can be desirable to get the same random number sequence multiple times\&. If the random number generator is called without first seeding it, the current time will be used as the seed\&.
.SS "Example"
The following code will count down from a random number to 1:
.PP
.PP
.nf

for i in (seq (random) -1 1)
        echo $i
        sleep
end
.fi
.PP
 
