.TH "return" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
return \- return - stop the current inner function 
.SH "return - stop the current inner function"
.PP
.SS "Synopsis"
\fCfunction NAME; [COMMANDS\&.\&.\&.;] return [STATUS]; [COMMANDS\&.\&.\&.;] end\fP
.SS "Description"
\fCreturn\fP halts a currently running function\&. The exit status is set to \fCSTATUS\fP if it is given\&.
.PP
It is usually added inside of a conditional block such as an \fCif\fP statement or a \fCswitch\fP statement to conditionally stop the executing function and return to the caller, but it can also be used to specify the exit status of a function\&.
.SS "Example"
The following code is an implementation of the false command as a fish function
.PP
.PP
.nf

function false
        return 1
end
.fi
.PP
 
