.TH "set_color" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
set_color \- set_color - set the terminal color 
.SH "set_color - set the terminal color"
.PP
.SS "Synopsis"
\fCset_color [-h --help] [-b --background COLOR] [COLOR]\fP
.SS "Description"
\fCset_color\fP changes the foreground and/or background color of the terminal\&. \fCCOLOR\fP is one of black, red, green, brown, yellow, blue, magenta, purple, cyan, white and normal\&.
.PP
If your terminal supports term256 (modern xterms and OS X Lion), you can specify an RGB value with three or six hex digits, such as A0FF33 or f2f\&. \fCfish\fP will choose the closest supported color\&.
.PP
The following options are available:
.PP
.IP "\(bu" 2
\fC-b\fP, \fC--background\fP \fCCOLOR\fP sets the background color\&.
.IP "\(bu" 2
\fC-c\fP, \fC--print-colors\fP prints a list of all valid color names\&.
.IP "\(bu" 2
\fC-h\fP, \fC--help\fP displays a help message and exit\&.
.IP "\(bu" 2
\fC-o\fP, \fC--bold\fP sets bold or extra bright mode\&.
.IP "\(bu" 2
\fC-u\fP, \fC--underline\fP sets underlined mode\&.
.PP
.PP
Calling \fCset_color normal\fP will set the terminal color to the default color of the terminal\&.
.PP
Some terminals use the --bold escape sequence to switch to a brighter color set\&. On such terminals, \fCset_color white\fP will result in a grey font color, while \fCset_color --bold white\fP will result in a white font color\&.
.PP
Not all terminal emulators support all these features\&.
.PP
\fCset_color\fP uses the terminfo database to look up how to change terminal colors on whatever terminal is in use\&. Some systems have old and incomplete terminfo databases, and may lack color information for terminals that support it\&.
.SS "Examples"
.PP
.nf
set_color red; echo 'Roses are red'
set_color blue; echo 'Violets are blue'
set_color 62A ; echo 'Eggplants are dark purple'
set_color normal; echo 'Normal is nice too'
.fi
.PP
 
