.TH "trap" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trap \- trap - perform an action when the shell receives a signal 
.SH "trap - perform an action when the shell receives a signal"
.PP
.SS "Synopsis"
\fCtrap [OPTIONS] [[ARG] SIGSPEC \&.\&.\&. ]\fP
.SS "Description"
\fCtrap\fP is a wrapper around the fish event delivery framework\&. It exists for backwards compatibility with POSIX shells\&. For other uses, it is recommended to define an \fCevent handler\fP\&.
.PP
The following parameters are available:
.PP
.IP "\(bu" 2
\fCARG\fP is the command to be executed on signal delivery\&.
.IP "\(bu" 2
\fCSIGSPEC\fP is the name of the signal to trap\&.
.IP "\(bu" 2
\fC-h\fP or \fC--help\fP displays help and exits\&.
.IP "\(bu" 2
\fC-l\fP or \fC--list-signals\fP prints a list of signal names\&.
.IP "\(bu" 2
\fC-p\fP or \fC--print\fP prints all defined signal handlers\&.
.PP
.PP
If \fCARG\fP and \fCSIGSPEC\fP are both specified, \fCARG\fP is the command to be executed when the signal specified by \fCSIGSPEC\fP is delivered\&.
.PP
If \fCARG\fP is absent (and there is a single SIGSPEC) or -, each specified signal is reset to its original disposition (the value it had upon entrance to the shell)\&. If \fCARG\fP is the null string the signal specified by each \fCSIGSPEC\fP is ignored by the shell and by the commands it invokes\&.
.PP
If \fCARG\fP is not present and \fC-p\fP has been supplied, then the trap commands associated with each \fCSIGSPEC\fP are displayed\&. If no arguments are supplied or if only \fC-p\fP is given, \fCtrap\fP prints the list of commands associated with each signal\&.
.PP
Signal names are case insensitive and the \fCSIG\fP prefix is optional\&.
.PP
The return status is 1 if any \fCSIGSPEC\fP is invalid; otherwise trap returns 0\&.
.SS "Example"
\fCtrap 'status &ndash;print-stack-trace' SIGUSR1\fP prints a stack trace each time the \fCSIGUSR1\fP signal is sent to the shell\&. 
