.TH "vared" 1 "Sat Oct 19 2013" "Version 2.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vared \- vared - interactively edit the value of an environment variable 
.SH "vared - interactively edit the value of an environment variable"
.PP
.SS "Synopsis"
\fCvared VARIABLE_NAME\fP
.SS "Description"
\fCvared\fP is used to interactively edit the value of an environment variable\&. Array variables as a whole can not be edited using \fCvared\fP, but individual array elements can\&.
.SS "Example"
\fCvared PATH[3]\fP edits the third element of the PATH array 
